company_blog/blog_posts/forms.py
from operator import sub
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms import validators
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):

    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("Post")

company_blog/blog_posts/views.py
from logging import log
from os import abort
import re
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from company_blog import db
from company_blog.models import BlogPost
from company_blog.blog_posts.forms import BlogPostForm


blog_posts = Blueprint("blog_posts", __name__)


#The views here are CRUD.

#1. CREATE
@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")

        return redirect(url_for('core.index'))
    
    return render_template('create_post.html', form=form)

#2. READ (VIEW)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    return render_template("blog_post.html", 
                            title=blog_post.title,
                            date=blog_post.date,
                            post=blog_post
                            )

#3. Update
@blog_posts.route("/<int:blog_post_id>/update", methods=["POST", "GET"])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.commit()
        flash("Blog Post Updated")

        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post.id))

    #prefill the form with old info so that the user can edit it instead of blank fields
    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    
    return render_template("create_post.html", title="Updating", form=form)


#4. delete
@blog_posts.route("/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)
    
    db.session.delete(blog_post)
    db.session.commit()
    flash("Blog Post deleted")

    return redirect(url_for("core.index"))

company_blog/core/views.py
from company_blog.blog_posts.views import blog_post
from flask import render_template, request, Blueprint
from company_blog.models import BlogPost

#setup blueprint
core = Blueprint("core", __name__)

@core.route("/")
def index():

    #paginate blog list
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)

    return render_template("index.html", blog_posts=blog_posts)

@core.route("/info")
def info():
    return render_template("info.html")

company_blog/users/views.py
"""
view related to the userZ:

1. register
2. login
3. logout
4. account (update UserForm)
5. user's list of blog posts

"""
from flask_login.login_manager import LoginManager
from flask_login.mixins import UserMixin
from wtforms import meta
from company_blog.users.forms import RegsitrationForm, LoginForm, UpdateUserForm
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from company_blog import db
from company_blog.models import User, BlogPost
from company_blog.users.picture_handler import add_profile_pic

#register blueprint
users = Blueprint('users', __name__)

#login
@users.route('/login', methods=["GET", "POST"])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        #query the user from the db to get an object of the User class
        user = User.query.filter_by(email=form.email.data).first() #email is unique

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Successfully logged in!")

            #this gets the url that the user was actually trying to get to before being redirected to the login page.
            next = request.args.get('next')

            if next == None or next[0] == "/":
                next = url_for("core.index")

            return redirect(next)

    return render_template("login.html", form=form)

 
#logout
@users.route("/logout")
def logout():
    
    logout_user() #default flask method
    return redirect(url_for('core.index'))

#register user (includes GET AND POST methods since it has form input)
@users.route("/register", methods=["GET", "POST"])
def register():
    
    form = RegsitrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, 
        username=form.username.data, 
        password=form.password.data
        )

        db.session.add(user)
        db.session.commit()
        flash("Thanks for registering!")

        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)


#account (update Userform)
@users.route("/account", methods=["POST", "GET"])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        #if user uploads a pic
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()
        flash("User Account Updated!")

        return redirect(url_for('users.account')) #or redirect('core.index')

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/')
    return render_template("account.html", profile_image=profile_image, form=form)

#user posts
@users.route('/<username>')
def user_posts(username):

    #paginate user blog posts
    page = request.args.get('page', 1, type=int)

    #get the first user (username is unique, should only be 1). if not found, return 404
    user = User.query.filter_by(username=username).first_or_404()

    #backref to the BlogPost db class to the users is author which is used here.  
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

company_blog/templates/account.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <div align="center">
            <h1> Welcome to the page for {{ current_user.username }}!</h1>
            <img align='center' src=" {{url_for('static', filename='profile_pics/' + current_user.profile_image)}} " alt="">
        </div>
    </div>

    <div class="container">
    <form method="POST", action="", enctype="multipart/form-data">
        
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class='form-group') }} 
            {{ form.username(class='form-control') }}
        </div>

        <div class="form-group">
            {{ form.email.label(class='form-group') }} 
            {{ form.email(class='form-control') }}
        </div>

        <div class="form-group">
            {{ form.picture.label(class='form-group') }} 
            {{ form.picture(class='form-control') }}
        </div>

        <div class="form-group">
            {{ form.submit(class='btn btn-primary') }}
        </div>
    </form>
    
    </div>
{% endblock content %}

company_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- boostrap, css, js -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title></title>
    </head>
    <body>
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href=" {{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" {{ url_for('core.info') }} ">About</a>
                    </li>

                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}"">Create Post</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href=" {{url_for('users.account') }} ">Account</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href=" {{url_for('users.logout') }} ">Logout</a>
                        </li>

                    {% else %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href=" {{url_for('users.login') }} ">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href=" {{url_for('users.register') }} ">Register</a>
                        </li>
                    {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        
        <!-- content block-->
        <div class="container">
            {% block content %}
            
            {% endblock content %}
        </div>
    </body>
</html>

company_blog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <h1> {{ title }}</h1>
        <h2>Written by: {{ post.author.usernanme }}</h2>
        <h3> Published: {{ post.date.strftime( '%B %d %Y')}}</h3>
        <p> {{ post.text }}</p>

        {# we have access to the current_user object since we're using flask_login #}
        {% if post.author == current_user %}
            <div>
                <a href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
                
                {# using bootsrap modal to add warning message before delete #}
                <button type="button" name="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal" >Delete</button>
            </div>
        {% endif %}
    </div>

    <!-- Modal for Pop Up-->
    {# https://getbootstrap.com/docs/4.1/components/modal/ #}
    {# Notice how the link with the id to the button above! #}
    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <p>Are you sure you want to delete this blog post?</p>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

            <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}s

company_blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <form action="" class="form-group" method="POST">

            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {{ form.title(class="form-control form-control-lg") }}
            </div>

            <div class="form-group">
                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-lg") }}
            </div>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

company_blog/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Company Blog</h1>
    </div>

    <!-- cards to view to the content -->
    <div class="container">

        {% for post in blog_posts.items  %}

            <div class="card">
                <div class="card-body">
                    <h2>
                        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id)}}" class="card-title"> {{post.title}}</a>
                    </h2>
                    <a href="{{ url_for('users.user_posts', username=post.author.username) }}"> Written By: {{ post.author.username}}</a>
                </div>
                <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
                <a class= "btn btn-primary" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id)}}"> Read Blog Post</a>
            </div>
        {% endfor %}

    </div>

    <!-- pagination (same as user_blog_post.html) -->
    <nav aria-label="Page Navigation Example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if blog_posts.page == page_num %}
                    <li class='page-item disabled'>
                        <a class="page-link" href="{{ url_for('core.index', page=page_num) }}"> {{ page_num }}</a>
                    </li>
                {% else %}
                    <li class='page-item'>
                        <a class="page-link" href="{{url_for('core.index',page=page_num) }}"> {{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

{% endblock content %}

company_blog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>About Us</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis veniam hic impedit, natus est modi suscipit earum recusandae dignissimos quasi. Consectetur, velit tempora consequuntur voluptatem blanditiis assumenda omnis rem pariatur.</p>
    </div>
{% endblock content %}

company_blog/templates/login.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">
    
        {{ form.hidden_tag() }}
        {{ form.email.label }}{{ form.email() }}<br>
        {{ form.password.label }}{{ form.password() }}<br>

        {{ form.submit() }}
    </form>

{% endblock content %}

company_blog/templates/register.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">
    
        {{ form.hidden_tag() }}
        {{ form.email.label }}{{ form.email }}<br>
        {{ form.username.label }}{{ form.username }}<br>
        {{ form.password.label }}{{ form.password }}<br>
        {{ form.pass_confirm.label }}{{ form.pass_confirm }}<br>

        {{ form.submit() }}
    </form>

{% endblock content %}

company_blog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}

    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>Welcome to the page for {{ user.username }}</h1>
                <img src="{{ url_for('static', filename='profile_pics/' + user.profile_image)}}">
            </div>
        </div>

        {% for post in blog_posts.items  %}

            <h2> <a href=" {{url_for('blog_posts.blog_post', blog_post_id=post.id)}} "> {{ post.title}} </a></h2>
            Written By: <a href="{{ url_for('users.user_posts', username=post.author.username)}}"> {{ post.author.username }}</a>
            <p class='text-muted'> Published on: {{ post.date.strftime("%Y-%m-%d")}}</p>
            <br>
            <p>{{post.text}}</p>
            <br>
    {% endfor %}

    </div>

    <!-- pagination in bootstrap -->
    <nav aria-label="Page Navigation Example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if blog_posts.page == page_num %}
                    <li class='page-item disabled'>
                        <a class="page-link" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}"> {{ page_num }}</a>
                    </li>
                {% else %}
                    <li class='page-item'>
                        <a class="page-link" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}"> {{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

{% endblock content %}